{"name": "test_2[4-5]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (4 + 5) > 9", "trace": "data1 = 4, data2 = 5\n\n    @pytest.mark.parametrize('data1,data2',[(2,3),(4,5),(6,7)])\n    def test_2(data1,data2):\n        case_data.case_test_record_list.append('3')\n>       assert data1+data2 > 9\nE       assert (4 + 5) > 9\n\nD:\\autotest\\cases\\system\\AF\\8040\\test_param.py:23: AssertionError"}, "parameters": [{"name": "data1", "value": "4"}, {"name": "data2", "value": "5"}], "start": 1614493648084, "stop": 1614493648084, "uuid": "8e760776-79e6-4939-85ac-b1f849cdfe49", "historyId": "5511c6fdfc0ee8ce66be30ccfb066c84", "testCaseId": "66c14860c93f84aeecc2424c28b86d59", "fullName": "cases.system.AF.8040.test_param#test_2", "labels": [{"name": "parentSuite", "value": "cases.system.AF.8040"}, {"name": "suite", "value": "test_param"}, {"name": "host", "value": "DESKTOP-H5OTV7O"}, {"name": "thread", "value": "13228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.system.AF.8040.test_param"}]}